global:
  scrape_interval: 15s        # Prometheus akan scrape tiap 15 detik
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mlflow_model'   # Job untuk model MLflow
    static_configs:
      - targets: ['localhost:8001']  # Port exporter Python
