name: Run Preprocessing Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - "preprocessing/**"
      - "*.csv"        # dataset baseline berubah â†’ workflow jalan

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Ahmad_Radesta.py

    - name: Commit processed dataset
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add preprocessing/processed_heart_failure_data.csv
        git commit -m "Update processed dataset [auto]" || echo "No changes to commit"
        git push
      continue-on-error: true

    - name: Upload processed dataset as artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed_dataset
        path: preprocessing/processed_heart_failure_data.csv
