name: Run Preprocessing Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - "Eksperimen_SML_Ahmad_Radesta/preprocessing/**"
      - "*.csv"

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug folder structure
      run: ls -R .

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Run preprocessing script
      run: |
        python "Eksperimen_SML_Ahmad_Radesta/preprocessing/automate_Ahmad_Radesta.py"

    - name: Move processed dataset
      run: |
        if [ -f processed_heart_failure_data.csv ]; then
          mv processed_heart_failure_data.csv "Eksperimen_SML_Ahmad_Radesta/preprocessing/processed_heart_failure_data.csv"
        fi

    - name: Commit and push outputs
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "Eksperimen_SML_Ahmad_Radesta/preprocessing/*"
        git commit -m "Update preprocessing outputs [auto]" || true
        git push || true
